# Generated by Django 2.2 on 2021-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='display_phone',
        ),
        migrations.AddField(
            model_name='category',
            name='alias',
            field=models.SlugField(default=None),
        ),
    ]
