# Generated by Django 2.2 on 2021-06-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20210616_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='restaurants.Category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='restaurants.Location'),
        ),
    ]
