# Generated by Django 2.2 on 2021-06-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20210616_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
