# Generated by Django 2.2 on 2021-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20210616_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categories',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(related_name='Category', to='restaurants.Category'),
        ),
    ]
