# Generated by Django 2.2 on 2021-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20210617_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address3',
        ),
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
