# Generated by Django 2.2 on 2021-06-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('restaurants', '0014_auto_20210617_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favorites',
            field=models.ManyToManyField(related_name='user_likes', to='login_reg_app.User'),
        ),
    ]
