# Generated by Django 2.2 on 2021-06-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='login_reg_app.User'),
        ),
    ]
