# Generated by Django 2.2 on 2021-06-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_auto_20210622_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
