# Generated by Django 2.2 on 2021-08-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_auto_20210623_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
